dist: focal

jdk:
  - oraclejdk15

services:
  - docker

sudo: true

before_script:
  - echo 'Europe/Zurich' | sudo tee /etc/timezone
  - sudo dpkg-reconfigure --frontend noninteractive tzdata

script:
  # Prepare installation process -------------------------------------------------
  - travis_fold start "Prepare_installation_process"
  - export HOME_ECLIPSE=/snap/bin
  - export VERSION_GRADLE=6.7.1

  - sudo apt update -q
  - travis_fold end   "Prepare_Installation_Process"

  - travis_fold start "Install_Eclipse"
  - sudo snap install --classic eclipse
  - travis_fold end   "Install_Eclipse"

  - travis_fold start "Install_Gradle"
  - wget -q https://services.gradle.org/distributions/gradle-${VERSION_GRADLE}-bin.zip -P /tmp
  - sudo unzip -d /opt/gradle /tmp/gradle-*.zip
  - export GRADLE_HOME=/opt/gradle/gradle-${VERSION_GRADLE}
  - export PATH=${GRADLE_HOME}/bin:${PATH}
  - travis_fold end   "Install_Gradle"

  - sudo apt install net-tools
  - netstat -tulpn | grep LISTEN
  - gradle --version
  - java -version

  - travis_fold start "Pull_And_Compile_Repository"
  - git pull
  - sudo chmod +x *.sh
  - sudo chmod +x lib/*.jar
  - sudo chmod +x scripts/*.sh
  - gradle copyJarToLib
  - travis_fold end   "Pull_And_Compile_Repository"
